/** Graph and resource endpoints, backed by the curated query library. */

import type { FastifyInstance } from "fastify";
import * as q from "../db/queries.js";
import { remediationInputFromGraph } from "../remediation/fromGraph.js";
import { remediationsFor } from "../remediation/remediation.js";

export function registerGraphRoutes(app: FastifyInstance): void {
  app.get("/api/summary", async () => q.summariseAccount());

  app.get<{ Querystring: { region?: string; kinds?: string; limit?: string } }>(
    "/api/graph",
    async (req) => {
      const kinds = req.query.kinds?.split(",").filter(Boolean);
      return q.fetchGraph({
        region: req.query.region,
        ...(kinds && kinds.length > 0 ? { kinds } : {}),
        limit: req.query.limit ? Number(req.query.limit) : undefined,
      });
    },
  );

  app.get<{ Params: { arn: string } }>("/api/resources/:arn", async (req, reply) => {
    const resource = await q.getResource(decodeURIComponent(req.params.arn));
    if (!resource) return reply.code(404).send({ error: "No such resource" });
    return reply.send({ resource });
  });

  /**
   * What you would run to fix this resource, and what it might break.
   *
   * Strictly a document endpoint: it returns strings. Nothing in this service
   * executes them, and there is deliberately no companion endpoint that does —
   * see `packages/shared/src/remediation.ts`. The commands are computed from
   * the same evidence the verdict came from, not generated by the model.
   */
  app.get<{ Params: { arn: string } }>("/api/resources/:arn/remediation", async (req, reply) => {
    const resource = await q.getResource(decodeURIComponent(req.params.arn));
    if (!resource) return reply.code(404).send({ error: "No such resource" });
    const remediations = remediationsFor(remediationInputFromGraph(resource as never));
    return reply.send({
      arn: resource.arn,
      remediations,
      note: "Generated for you to review and run yourself. dave.io holds read-only access and will never apply these.",
    });
  });

  app.get<{ Querystring: { q?: string } }>("/api/search", async (req) => ({
    results: req.query.q ? await q.searchResources({ text: req.query.q }) : [],
  }));

  /** Findings, for the dashboard panels. */
  app.get("/api/findings", async () => {
    const [publicResources, adminPrincipals, idle, exposed, unprotected] = await Promise.all([
      q.findPublicResources({ limit: 50 }),
      q.findAdminPrincipals({ limit: 50 }),
      q.findIdleResources({ limit: 50 }),
      q.findOpenSecurityGroups({ limit: 50 }),
      q.findUnprotectedBuckets({ limit: 50 }),
    ]);
    return { publicResources, adminPrincipals, idle, exposed, unprotected };
  });
}
