/**
 * Graph and resource reads, backed by the curated query library.
 *
 * Thin by design: `db/queries.ts` is already the boundary that decides what
 * can be asked of the graph (ADR-005), and wrapping each query in a method
 * that reshapes it would put the same decision in two places. What this adds
 * is the small amount of policy the HTTP layer should not hold — parsing a
 * comma-separated filter, and deciding that a search with no term is an empty
 * result rather than everything.
 */

import { Injectable, NotFoundException } from "@nestjs/common";

import * as q from "../db/queries.js";
import { remediationInputFromGraph } from "../remediation/fromGraph.js";
import { remediationsFor } from "../remediation/remediation.js";

@Injectable()
export class GraphService {
  summary() {
    return q.summariseAccount();
  }

  graph(params: { region?: string; kinds?: string; limit?: string }) {
    const kinds = params.kinds?.split(",").filter(Boolean);
    return q.fetchGraph({
      region: params.region,
      ...(kinds && kinds.length > 0 ? { kinds } : {}),
      limit: params.limit ? Number(params.limit) : undefined,
    });
  }

  async resource(arn: string) {
    const resource = await q.getResource(decodeURIComponent(arn));
    if (!resource) throw new NotFoundException({ error: "No such resource" });
    return { resource };
  }

  /**
   * What you would run to fix this resource, and what it might break.
   *
   * Strictly a document: it returns strings. Nothing in this service executes
   * them, and there is deliberately no companion endpoint that does — see
   * `packages/shared/src/remediation.ts`. The commands are computed from the
   * same evidence the verdict came from, not generated by the model.
   */
  async remediation(arn: string) {
    const resource = await q.getResource(decodeURIComponent(arn));
    if (!resource) throw new NotFoundException({ error: "No such resource" });
    return {
      arn: resource.arn,
      remediations: remediationsFor(remediationInputFromGraph(resource as never)),
      note: "Generated for you to review and run yourself. dave.io holds read-only access and will never apply these.",
    };
  }

  async search(text?: string) {
    // No term is an empty result, not the whole account.
    return { results: text ? await q.searchResources({ text }) : [] };
  }

  /** Findings, for the dashboard panels. */
  async findings() {
    const [publicResources, adminPrincipals, idle, exposed, unprotected] = await Promise.all([
      q.findPublicResources({ limit: 50 }),
      q.findAdminPrincipals({ limit: 50 }),
      q.findIdleResources({ limit: 50 }),
      q.findOpenSecurityGroups({ limit: 50 }),
      q.findUnprotectedBuckets({ limit: 50 }),
    ]);
    return { publicResources, adminPrincipals, idle, exposed, unprotected };
  }
}
