/**
 * The fictional customer account that the scanner discovers.
 *
 * The brief asks for mock data "interesting enough that the agent's questions
 * have non-obvious answers". Every element below exists to make some question
 * require reasoning rather than a field lookup. The traps are deliberate:
 *
 *  - A bucket that is public via *policy* sits next to one that looks public
 *    but is neutralised by its public-access block. "Is it public?" cannot be
 *    answered by reading one field.
 *
 *  - The production database is not publicly accessible and sits in a private
 *    subnet, yet it IS reachable from the internet - across three security
 *    group hops, and again by a shorter path through a bastion. "What can
 *    reach it?" requires walking the graph.
 *
 *  - A second database has PubliclyAccessible=true and is reachable by nobody,
 *    because its security group opens no ports. The naive answer is wrong.
 *
 *  - One admin role carries the AdministratorAccess managed policy; another
 *    grants the same power through an *inline* `*:*` statement and an
 *    innocuous name. Finding both means reading policy documents, not names.
 *
 * Names are stable and unique, so evals can express ground truth by name and
 * resolve to ARNs at run time (moto assigns random ids).
 */

export const ACCOUNT_ID = process.env.MOCK_AWS_ACCOUNT_ID ?? "123456789012";

export const PROD_REGION = "us-east-1";
export const STAGING_REGION = "eu-west-1";
export const LEGACY_REGION = "ap-southeast-1";

export const SEEDED_REGIONS = [PROD_REGION, STAGING_REGION, LEGACY_REGION] as const;

/** Tags applied across the estate, so the agent can reason about ownership. */
export const TAGS = {
  prod: { Environment: "production", Owner: "platform", CostCenter: "eng-core" },
  staging: { Environment: "staging", Owner: "platform", CostCenter: "eng-core" },
  legacy: { Environment: "legacy", Owner: "unknown" },
} as const;

/**
 * Ground truth for the eval suite, expressed by resource name.
 *
 * This is the answer key. It is written by hand from the topology above, NOT
 * generated by the same code that builds the graph - otherwise a bug in the
 * analysers would be graded against itself and always pass.
 */
export const GROUND_TRUTH = {
  /** Buckets reachable by anonymous principals. */
  publicBuckets: ["northwind-public-assets"],

  /**
   * Buckets with a wildcard-principal policy that is NOT effective, because
   * the account- or bucket-level public access block overrides it.
   */
  blockedPublicBuckets: ["northwind-reports"],

  /** Roles with effective `*:*`. */
  adminRoles: ["NorthwindAdminRole", "LegacyDeployRole", "UnusedAdminRole"],

  /**
   * Users with effective `*:*`.
   *
   * Separate from roles because they were separately missed: the scanner
   * inventoried users without their policies, so an account administered
   * entirely through IAM users reported no administrators at all. A standing
   * user with long-lived keys is not a lesser finding than an admin role.
   */
  adminUsers: ["northwind-ci-deploy", "northwind-backup-agent"],

  /** Users that must NOT be flagged - the negative class for the above. */
  nonAdminUsers: ["northwind-metrics-reader"],

  /** Admin roles with an inline rather than managed grant. */
  inlineAdminRoles: ["LegacyDeployRole"],

  /** Admin users whose grant is inline, under an unrevealing policy name. */
  inlineAdminUsers: ["northwind-backup-agent"],

  /** Admin roles nothing assumes or attaches to. */
  unusedAdminRoles: ["UnusedAdminRole"],

  /** Resources reachable from the public internet, directly or transitively. */
  internetReachable: [
    "prod-web-1",
    "prod-web-2",
    "prod-bastion",
    "staging-rdp-host",
    "northwind-prod-db",
  ],

  /**
   * The production database is reachable by two distinct paths. Any correct
   * answer to "what can reach the production RDS instance?" must include the
   * bastion; a good one mentions both routes.
   */
  prodDbReachablePaths: [
    ["Internet", "prod-web-1", "prod-app-1", "northwind-prod-db"],
    ["Internet", "prod-bastion", "northwind-prod-db"],
  ],

  /** Flagged PubliclyAccessible but unreachable - no security group opens a port. */
  falsePositivePublicDb: ["analytics-db"],

  /** EC2 instances outside a private subnet. */
  instancesInPublicSubnets: ["prod-web-1", "prod-web-2", "prod-bastion", "staging-rdp-host"],

  /**
   * Billable but idle, by structural signal alone (attached to nothing,
   * associated with nothing, or stopped).
   *
   * `northwind-logs-archive` is deliberately NOT here. It is genuinely
   * unused, but proving that needs CloudWatch request metrics that this
   * scanner does not collect - so it would be a lucky guess, not a finding.
   */
  idleResources: [
    "orphaned-vol-1",
    "orphaned-vol-2",
    "legacy-orphaned-vol",
    "old-jenkins",
    "legacy-nat",
  ],

  /** Security groups exposing sensitive ports to the whole internet. */
  sensitivePortsOpenToWorld: [
    { group: "prod-bastion-sg", port: 22 },
    { group: "staging-rdp-sg", port: 3389 },
  ],

  /** A Lambda function executing with administrator privileges. */
  overPrivilegedFunctions: ["legacy-image-resizer"],
} as const;
