/**
 * The fictional customer account the scanner discovers. Every element exists to
 * make some question need reasoning rather than a field lookup:
 *
 *  - a bucket public via *policy* beside one that looks public but is
 *    neutralised by its access block
 *  - the production database, private and not publicly accessible, yet
 *    reachable from the internet across three security group hops
 *  - a second database with PubliclyAccessible=true that nobody can reach,
 *    because its group opens no ports - the naive answer is wrong
 *  - one admin role via the managed policy, another via an inline `*:*` under
 *    an innocuous name: finding both means reading documents, not names
 *
 * Names are stable and unique so evals can state ground truth by name and
 * resolve ARNs at run time (moto assigns random ids).
 */

export const ACCOUNT_ID = process.env.MOCK_AWS_ACCOUNT_ID ?? "123456789012";

export const PROD_REGION = "us-east-1";
export const STAGING_REGION = "eu-west-1";
export const LEGACY_REGION = "ap-southeast-1";

export const SEEDED_REGIONS = [PROD_REGION, STAGING_REGION, LEGACY_REGION] as const;

/** Tags applied across the estate, so the agent can reason about ownership. */
export const TAGS = {
  prod: { Environment: "production", Owner: "platform", CostCenter: "eng-core" },
  staging: { Environment: "staging", Owner: "platform", CostCenter: "eng-core" },
  legacy: { Environment: "legacy", Owner: "unknown" },
} as const;

/**
 * Ground truth for the eval suite, expressed by resource name.
 *
 * This is the answer key. It is written by hand from the topology above, NOT
 * generated by the same code that builds the graph - otherwise a bug in the
 * analysers would be graded against itself and always pass.
 */
export const GROUND_TRUTH = {
  /** Buckets reachable by anonymous principals. */
  publicBuckets: ["northwind-public-assets"],

  /**
   * Buckets with a wildcard-principal policy that is NOT effective, because
   * the account- or bucket-level public access block overrides it.
   */
  blockedPublicBuckets: ["northwind-reports"],

  /** Roles with effective `*:*`. */
  adminRoles: ["NorthwindAdminRole", "LegacyDeployRole", "UnusedAdminRole"],

  /**
   * Users with effective `*:*`.
   *
   * Separate from roles because they were separately missed: the scanner
   * inventoried users without their policies, so an account administered
   * entirely through IAM users reported no administrators at all. A standing
   * user with long-lived keys is not a lesser finding than an admin role.
   */
  adminUsers: ["northwind-ci-deploy", "northwind-backup-agent"],

  /** Users that must NOT be flagged - the negative class for the above. */
  nonAdminUsers: ["northwind-metrics-reader"],

  /**
   * The service-linked role, named here so a test can assert the fixture still
   * contains an ARN long enough to be interesting.
   *
   * Every other role in this account has a short, path-less name, and that gap
   * let a routing bug reach a real user: percent-encoded, a service-linked
   * role's ARN is 136 characters against Fastify's 100-character default cap,
   * and clicking one returned HTTP 414 (engineering log #37). A fixture that
   * cannot express the shape cannot catch the bug.
   */
  longArnRolePath: "/aws-service-role/elasticloadbalancing.amazonaws.com/",
  longArnRoleName: "AWSServiceRoleForElasticLoadBalancing",

  /** Admin roles with an inline rather than managed grant. */
  inlineAdminRoles: ["LegacyDeployRole"],

  /** Admin users whose grant is inline, under an unrevealing policy name. */
  inlineAdminUsers: ["northwind-backup-agent"],

  /** Admin roles nothing assumes or attaches to. */
  unusedAdminRoles: ["UnusedAdminRole"],

  /** Resources reachable from the public internet, directly or transitively. */
  internetReachable: [
    "prod-web-1",
    "prod-web-2",
    "prod-bastion",
    "staging-rdp-host",
    "northwind-prod-db",
  ],

  /**
   * The production database is reachable by two distinct paths. Any correct
   * answer to "what can reach the production RDS instance?" must include the
   * bastion; a good one mentions both routes.
   */
  prodDbReachablePaths: [
    ["Internet", "prod-web-1", "prod-app-1", "northwind-prod-db"],
    ["Internet", "prod-bastion", "northwind-prod-db"],
  ],

  /** Flagged PubliclyAccessible but unreachable - no security group opens a port. */
  falsePositivePublicDb: ["analytics-db"],

  /** EC2 instances outside a private subnet. */
  instancesInPublicSubnets: ["prod-web-1", "prod-web-2", "prod-bastion", "staging-rdp-host"],

  /**
   * Billable but idle, by structural signal alone (attached to nothing,
   * associated with nothing, or stopped).
   *
   * `northwind-logs-archive` is deliberately NOT here. It is genuinely
   * unused, but proving that needs CloudWatch request metrics that this
   * scanner does not collect - so it would be a lucky guess, not a finding.
   */
  idleResources: [
    "orphaned-vol-1",
    "orphaned-vol-2",
    "legacy-orphaned-vol",
    "old-jenkins",
    "legacy-nat",
    /**
     * Added after the audit that found it missing. The rule for it existed and
     * was correct; the collector passed moto's empty-string "not associated"
     * through as a non-null value, so the address read as associated and was
     * silently never reported. The answer key had the same omission, so the
     * idle check passed (engineering log #30).
     */
    "orphaned-eip",
  ],

  /** Security groups exposing sensitive ports to the whole internet. */
  sensitivePortsOpenToWorld: [
    { group: "prod-bastion-sg", port: 22 },
    { group: "staging-rdp-sg", port: 3389 },
  ],

  /** A Lambda function executing with administrator privileges. */
  overPrivilegedFunctions: ["legacy-image-resizer"],
} as const;
